### ISSUE TITLE
Calling the filter causes the scrollbar to jump

### ISSUE THREAD

**Issue by Elindalyne** [thinkloop/knockout-js-progressive-filter#1]
I'm not really sure if I'm missing something but calling the filter appears to cause the scrollbar to jump to a higher point on the page.

Here is a fiddle to demonstrate my point - http://jsfiddle.net/cm65R/18/

I'm trying to find a workaround, but nothing appears to be working and could potentially be jarring to end users.

**Comment by thinkloop** [comment]
Hello,

Are you referring to when the page loads, and the items are added progressively, that the scrollbar shifts to accommodate the loading items?

If so, this is expected, as the div expands while items are added progressively. If done right, you can use these ui changes as natural and more relevant "loading animations" (instead of an informationless spinner, for example). If you would like to avoid shifting, you will have to build logic to do that. A couple of options I can think of without more info:
- Calculate your viewport size and slice your filtered items so that you only display as many as can fit on screen, then show more items on user action like scroll (see infinite scroll extender: https://github.com/thinkloop/knockout-js-infinite-scroll)
- Make your div "overflow: hidden" or "overflow: visible", and only make it "overflow-y: scroll" on hover

**Comment by Elindalyne** [comment]
Maybe here is a better example of the behavior I'm talking about.

http://jsfiddle.net/cm65R/21/

Basically unless the progressively filtered array is at the top of the page, the your page will jump. This is an issue for me because I'm loading data and templates via ajax with a variable # of items in them. From there users can page through, sort, or filter the data, which triggers the load of entirely new items in the observable array.

**Comment by thinkloop** [comment]
I see there is a 600px div above the list in the fiddle. If you click "get more stuff", the list is cleared then repopulated progressively, at the same time the scrollbar shifts to accommodate the growing and shrinking list. Is this scrollbar behavior what you are talking about?

**Comment by Elindalyne** [comment]
That is the behavior I'm talking about... Hearing you phrase things the way you did makes me feel pretty silly for reporting this as a bug... 

Still, I am at a bit of a loss as to what I could potentially do to mitigate the screen movement.

**Comment by thinkloop** [comment]
There are a few different ways you can consider to mitigate this. For example, right now the progressive filter first clears the list, then rebuilds it (causing the scrollbar to shift). What you could do, is rather than clearing the list first, simply start iterating through it, compare each item as you go, and replace "bad" items with their new "good" counterparts - at the end remove any extra items. This will keep the list length, and therefore your scrollbar, relatively consistent. 

Another option is to filter the collection progressively behind the scenes, but only display it when all the items are ready. Right now the display is updated as each item is filtered, if you wait until the collection is filtered, you can replace the entire list with a new list mitigating the scrollbar issue.

Finally you can consider handling it visually. You can, for example, make it so that scrollbars are only visible on hover, or when the collection is finished filtering.

The right solution depends on your specific use-case, let me know if you need help implementing one of these methods.

**Comment by Elindalyne** [comment]
I ended up incorporating the the page movement into the transitions on the page. Thanks for your help.

**Comment by thinkloop** [comment]
Good to hear - if what you're working on is up on a domain somewhere I'd love to see it.
